[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
name = "shared"
crate-type = ["rlib"]



[dependencies]
chrono = "0.4.29"
derivative = "2.2.0"
fern = { version = "0.6.2", features = ["colored"] }
log = "0.4.20"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
rust-embed = { version = "6.4.2", features = ["interpolate-folder-path",  "debug-embed"] }

