[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
name = "shared"
crate-type = ["rlib"]



[dependencies]
chrono = "0.4.29"
fern = { version = "0.6.2", features = ["colored"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
rust-embed = { version = "6.4.2", features = ["interpolate-folder-path",  "debug-embed"] }
bincode = "1.3.3"
thiserror.workspace = true
serde.workspace =true
ggez.workspace = true
derivative.workspace = true
log.workspace = true
